#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['autosnapgene']

package_data = \
{'': ['*'],
 'autosnapgene': ['.hypothesis/*',
                  '.hypothesis/examples/*',
                  '.pytest_cache/*',
                  '.pytest_cache/v/*',
                  '.pytest_cache/v/cache/*']}

install_requires = \
['docopt', 'arrow', 'autoprop', 'nonstdlib', 'more_itertools']

entry_points = \
{'console_scripts': ['autosnapgene = autosnapgene.main:main']}

setup(name='autosnapgene',
      version='0.0.0',
      description='Provide an API for parsing SnapGene *.dna files.',
      author='Kale Kundert',
      author_email='kale@thekunderts.net',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='~=3.7',
     )
